[package]
name = "Otaniemipeli"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
postgres = "0.19.10"
rouille = "3.6.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"