[package]
name = "Otaniemipeli"
version = "0.1.0"
edition = "2021"

[dependencies]
deadpool-postgres = "0.14.1"
dotenvy = "0.15.7"
postgres = "0.19.10"
rouille = "3.6.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-postgres = "0.7.13"
tokio = { version = "1.45.1", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = "1.0.98"
once_cell = "1.21.3"
