services:
  database:
    container_name: kanta
    image: postgres:17.0
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
    ports:
      - "${PUBLIC_PG_PORT}:${PUBLIC_PG_PORT}"
    env_file:
      - .env

  database-migrations:
    image: flyway/flyway:11
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./migrations:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate

  app:
    build: .
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
volumes:
  db_data: