insert into boards (name) values ('2025-lauta'), ('2001-lauta'), ('1985-lauta');
insert into games (name, board) values
                                    ('vujuviikon peli', 1),
                                    ('fuksipeli', 2),
                                    ('vaalikokous', 3),
                                    ('vujuviikko', 2),
                                    ('fuksipeli', 1),
                                    ('vaalikokous', 1),
                                    ('vujuviikko', 2),
                                    ('fuksipeli', 3),
                                    ('40v peli', 2),
                                    ('40v peli', 1),
                                    ('40v peli', 1),
                                    ('vaalikokous', 3);
insert into ingredients (name, abv, carbonated) values
                                                              ('beer', 4.7, true),
                                                              ('slime', 40.0, false),
                                                              ('red wine', 15.0, false),
                                                              ('cider', 5.3, true),
                                                              ('coca cola', 0.0, true),
                                                              ('vodka', 38.0, false),
                                                              ('tequila', 40.0, false),
                                                              ('fernet-branca', 39.0, false),
                                                              ('thunder', 12.0, false),
                                                              ('lonkero', 5.5, true),
                                                              ('vichy', 0.0, true),
                                                              ('a12 denat', 80.0, false),
                                                              ('energy drink', 0.0, true),
                                                              ('punch', 40.0, false),
                                                              ('jallu', 38.0, false),
                                                              ('orange juice', 0.0, false),
                                                              ('jägermeister', 40.0, false),
                                                              ('minttu', 40.0, false),
                                                              ('trocadero', 0.0, true),
                                                              ('absinthe', 66.0, false),
                                                              ('mehukatti', 0.0, false),
                                                              ('salmari', 32.0, false),
                                                              ('banana liqueur', 20.0, false);