insert into boards (name) values ('Lauta 2025'), ('Lauta 2001'), ('Lauta 1985');
insert into ingredients (name, abv, carbonated) values        ('Kalja', 4.7, true),
                                                              ('Slime', 40.0, false),
                                                              ('Punaviini', 15.0, false),
                                                              ('Siideri', 5.3, true),
                                                              ('Coca Cola', 0.0, true),
                                                              ('Koskenkorva', 38.0, false),
                                                              ('Tequila', 40.0, false),
                                                              ('Fernet-Branca', 39.0, false),
                                                              ('Thunder', 12.0, false),
                                                              ('Lonkero', 5.5, true),
                                                              ('Vichy', 0.0, true),
                                                              ('A12 Denat', 80.0, false),
                                                              ('Energia Juoma', 0.0, true),
                                                              ('Punssi', 40.0, false),
                                                              ('Jaloviina', 38.0, false),
                                                              ('Appelsiinimehu', 0.0, false),
                                                              ('Jägermeister', 40.0, false),
                                                              ('Minttu', 40.0, false),
                                                              ('Trocadero', 0.0, true),
                                                              ('Absintti', 66.0, false),
                                                              ('Mehukatti', 0.0, false),
                                                              ('Salmari', 32.0, false),
                                                              ('Banaanilikööri', 20.0, false);
INSERT INTO drinks (name) VALUES ('Kalja'), ('AS-huikka'), ('Slime'),
                              ('Terästetty Kokis'), ('Siideri'),
                              ('Punaviini'), ('Tequila'),
                              ('Fernet-Branca'), ('Thunder'),
                              ('Vichy'), ('Pirtu'), ('Energiajuoma'),
                              ('Kuulalaakeri'), ('Korjaussarja'),
                              ('Vodka'), ('Lammen vesi'), ('Suohauta'),
                              ('Jallu'), ('Trocadero'),
                              ('Terästetty Trocadero'), ('Absintti'),
                              ('Pöhkötaksi'), ('Apoptoosi'),
                              ('Lonkero'), ('Kokis'), ('Varasto');
INSERT INTO drink_ingredients (drink_id, ingredient_id, quantity) VALUES
                                (1, 1, 33),
                                (2, 1, 11),
                                (2, 4, 11),
                                (2, 3, 11),
                                (3, 2, 4),
                                (4, 5, 33),
                                (4, 6, 4),
                                (5, 4, 33),
                                (6, 3, 15),
                                (7, 7, 4),
                                (8, 8, 4),
                                (9, 9, 20),
                                (10, 11, 33),
                                (11, 12, 4),
                                (12, 13, 33),
                                (13, 15, 2),
                                (13, 14, 2),
                                (14, 16, 30),
                                (14, 6, 8),
                                (15, 6, 4),
                                (16, 10, 33),
                                (16, 17, 4),
                                (17, 15, 2),
                                (17, 6, 2),
                                (17, 18, 2),
                                (18, 15, 4),
                                (19, 19, 33),
                                (20, 19, 29),
                                (20, 6, 4),
                                (21, 20, 4),
                                (22, 21, 2),
                                (22, 12, 2),
                                (23, 22, 2),
                                (23, 23, 2),
                                (24, 10, 33),
                                (25, 5, 33),
                                (26, 16, 2),
                                (26, 12, 2);
INSERT INTO places (place_name, rule) VALUES ('Tietotien Metro'),
                                             ('Normaali Ruutu'),
                                             ('A-bloc'),
                                             ('Raide Jokeri'),
                                             ('Alvari'),
                                             ('Olohuone'),
                                             ('Database');
INSERT INTO board_places (board_id, place_number, place_id) VALUES
                                                                      (1, 1, 1),
                                                                      (1, 2, 2),
                                                                      (1, 3, 2),
                                                                      (1, 4, 2),
                                                                      (1, 5, 3),
                                                                      (1, 6, 2),
                                                                      (1, 7, 4);
